# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0), null=True),
        ),
    ]
