# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20170725_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
